env:
  - GHCVERSION="ghc822" NIXPKGS_TESTS="yes"

language: nix

script: nix-build --argstr compiler "$GHCVERSION"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/76ed871ff977c0ed653f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
