language: nix

sudo: true

cache:
  directories:
    - /nix/store

cache:
  timeout: 10000

env:
  - GHCVERSION=ghc822 NIXPKGS_TESTS=yes MATCHING_TESTS=yes TRACING=true  STRICT=true
  - GHCVERSION=ghc822 NIXPKGS_TESTS=yes MATCHING_TESTS=yes TRACING=false STRICT=true
  - GHCVERSION=ghc842 NIXPKGS_TESTS=yes MATCHING_TESTS=yes TRACING=false STRICT=false"

script:
  - nix-build --argstr compiler $GHCVERSION --arg doTracing $TRACING --arg doStrict $STRICT

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0312b18473340459d3e
    on_success: change
    on_failure: always
    on_start: never
