language: nix

sudo: false

cache:
  directories:
    - /nix
  timeout: 100000

install:
  - nix-shell --argstr compiler ghc822 --run true
  - nix-shell --argstr compiler ghc842 --run true

env:
  global:
    - NIXPKGS_TESTS=yes
    - MATCHING_TESTS=yes
  matrix:
    - GHCVERSION=ghc822 TRACING=true
    - GHCVERSION=ghc822 TRACING=false
    - GHCVERSION=ghc822 STRICT=true
    - GHCVERSION=ghc822 STRICT=false
    - GHCVERSION=ghc822 PROFILING=true
    - GHCVERSION=ghc822 PROFILING=false
    - GHCVERSION=ghc842 TRACING=true
    - GHCVERSION=ghc842 TRACING=false
    - GHCVERSION=ghc842 STRICT=true
    - GHCVERSION=ghc842 STRICT=false
    - GHCVERSION=ghc842 PROFILING=true
    - GHCVERSION=ghc842 PROFILING=false

matrix:
  allow_failures:
    - env: GHCVERSION=ghc842 STRICT=true
  exclude:
    - env: GHCVERSION=ghc822 STRICT=false

script:
  - nix-build --argstr compiler $GHCVERSION --arg doProfiling $PROFILING --arg doTracing $TRACING --arg doStrict $STRICT

branches:
  only:
    - master
    - pending

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b0312b18473340459d3e
    on_success: change
    on_failure: always
    on_start: never
