name: "Nixpkgs, GHCJS, Linux"
on:
  # On Git changes in PR
  pull_request:
  # On Git changes of the master
  push:
    branches:
      - master
  schedule:
    # Every day at 03:45
    - cron: "45 05 * * *"
env:
  compiler: "ghcjs"
  ghcjsTmpLogFile: "/tmp/ghcjsTmpLogFile.log"
  ghcjsLogTailLength: "10000"
jobs:
  build10:
    name: GHCJS
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Determined nix-build
      run: ./build.sh
