name: "Nixpkgs, GHCJS, Linux"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Every day at 05:45
    - cron: "45 05 * * *"

env:
  compiler: "ghcjs"
  ghcjsTmpLogFile: "/tmp/ghcjsTmpLogFile.log"
  ghcjsLogTailLength: "10000"

jobs:
  build10:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Determined nix-build
      run: ./build.sh
