name: "Nixpkgs, Linux, main"

# When to trigger builds
on:
  # On Git changes in PR
  pull_request:
  # On Git changes of the master
  push:
    branches:
      - master
  schedule:
    # Every day at 03:45
    - cron: "45 03 * * *"


env:
  ###
  ### NOTE: This configuration uses `build.sh` interface, which uses `default.nix` interface, which exposes the Nixpkgs Haskell Lib interface.
  ###
  ### Documentation of this settings is mosly in `default.nix`, since most settings it Nixpkgs related
  ### and the other part of keys explained in `build.sh`, since those address external procedures aound the builds.
  ### Additional documentation is in Nixpkgs Haskell.lib: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/lib.nix
  ###
  useRev: "true"
  rev: "nixos-unstable"
  cachixAccount: "replaceWithProjectNameInCachix"
  allowInconsistentDependencies: "false"
  doJailbreak: "false"
  doCheck: "true"
  sdistTarball: "false"
  buildFromSdist: "false"
  buildStrictly: "false"
  failOnAllWarnings: "false"
  enableDeadCodeElimination: "false"
  disableOptimization: "true"
  linkWithGold: "true"
  enableLibraryProfiling: "false"
  enableExecutableProfiling: "false"
  doTracing: "false"
  enableDWARFDebugging: "false"
  doStrip: "false"
  enableSharedLibraries: "true"
  enableStaticLibraries: "false"
  enableSharedExecutables: "false"
  justStaticExecutables: "false"
  enableSeparateBinOutput: "false"
  checkUnusedPackages: "false"
  doHaddock: "false"
  doHyperlinkSource: "false"
  doCoverage: "false"
  doBenchmark: "false"
  generateOptparseApplicativeCompletions: "false"
  executableNamesToShellComplete: '[ "replaceWithExecutableName" ]'


jobs:

  # NOTE: Basic example
  build10:
    name: "NixOS-unstable channel, Strict build, default GHC (8.8.3)"
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Determined nix-build
      run: ./build.sh


  # NOTE: Example of customization using Nixpkgs Haskell Lib API
  build20:
    name: "Release-quality test, SDist, Optimization, Benchmark, Haddock, GHC 8.10.1, Nix shell"
    runs-on: ubuntu-latest
    env:
      compiler: "ghc8101"
      buildFromSdist: "true"
      linkWithGold: "true"
      doHaddock: "true"
      doHyperlinkSource: "true"
      doBenchmark: "true"
      disableOptimization: "false"
      enableDeadCodeElimination: "true"
      generateOptparseApplicativeCompletions: "false"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Determined nix-build
      run: ./build.sh


  # NOTE: Build on latest stable NixOS release
  build30:
    name: "NixOS 20.03 stable channel, default GHC (8.8.3)"
    runs-on: ubuntu-latest
    env:
      rev: "nixos-20.03"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Determined nix-build
      run: ./build.sh


  # NOTE: This would additionally test that the Nix shell customization of the project works.
  # By default *this setup provides local hoogle and generates database of project documentation
  build40:
    name: "Test Nix-shell & supplied locall Hoogle DB"
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Test Nix-shell
      run: nix-shell --command 'echo "Evaluated, loaded and entered $IN_NIX_SHELL Nix shell env."'
    - name: Test Nix-shell local Hoogle DB
      run: nix-shell --command 'hoogle True'


  # Other samples of tests used in the project see in the directory
